server:
  port: 8040
spring:
  application:
    name: lottery-gateway
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
zuul:
  sensitive-headers: null
  routes:
    c1:
      url: http://localhost:9001/
      path: /c1/front/**
    c2:
      url: http://localhost:8081/
      path: /c2/front/**